source 'https://github.com/CocoaPods/Specs.git'

target 'ALiSSO', :exclusive => true do
  pod "ALiSSO", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ALiSSO", :path => "../"

  
end
