source 'https://github.com/CocoaPods/Specs.git'

target 'ALiOSS', :exclusive => true do
  pod "ALiOSS", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ALiOSS", :path => "../"

  
end
